export default cleanData = [
    {
        genre:"衛浴",
        pic:"123",
        todos:[
            {
                key:1,
                title:"牙刷1",
                note:"爸爸",
                day:57,
                limit:60,
                safe:true,
                normal:false,
                danger:false
            },
            {
                key:2,
                title:"牙刷11",
                note:"爸爸",
                day:"57",
                
                safe:true,
                normal:false,
                danger:false
            },
            {
                key:3,
                title:"牙刷111",
                note:"爸爸",
                day:"57",
                safe:true,
                normal:false,
                danger:false
            },
            {
                key:4,
                title:"牙刷1111",
                note:"爸爸",
                day:"57",
                safe:false,
                normal:true,
                danger:false
            }
        ]
    },
    {
        genre:"廚房",
        pic:"123",
        todos:[
            {
                key:5,
                title:"牙刷2",
                note:"爸爸",
                day:"57",
                safe:false,
                normal:true,
                danger:false
            },
            {
                key:6,
                title:"牙刷22",
                note:"爸爸",
                day:"57",
                safe:true,
                normal:false,
                danger:true
            }
        ]
    },
    {
        genre:"起居",
        pic:"123",
        todos:[
            {
                key:7,
                title:"牙刷3",
                note:"爸爸",
                day:"57",
                state:1
            },
            {
                key:8,
                title:"牙刷33",
                note:"爸爸",
                day:"57",
                state:3
            }
        ]
    },
    {
        genre:"其他",
        pic:"123",
        todos:[
            {
                key:9,
                title:"牙刷4",
                note:"爸爸",
                day:"57",
                state:1
            },
            {
                key:10,
                title:"牙刷44",
                note:"爸爸",
                day:"57",
                state:3
            }
        ]
    },
    {
        genre:"全部",
        pic:"123",
        todos:[
            {
                key:11,
                title:"牙刷5",
                note:"爸爸",
                day:"57",
                state:1
            },
            {
                key:12,
                title:"牙刷55",
                note:"爸爸",
                day:"57",
                state:3
            }
        ]
    }


];