export default cleanData = [
    {
        id:1,
        genre:"衛浴",
        pic:"https://github.com/s110719005/app_final_pic/blob/master/pic_bathroom2.png?raw=true",
        todos:[
            {
                key:"1",
                title:"牙刷1",
                note:"爸爸",
                day:57,
                limit:60,
                safe:true,
                normal:false,
                danger:false
            },
            {
                key:"2",
                title:"牙刷11",
                note:"爸爸",
                day:"57",
                
                safe:true,
                normal:false,
                danger:false
            },
            {
                key:"3",
                title:"牙刷111",
                note:"爸爸",
                day:"57",
                safe:true,
                normal:false,
                danger:false
            },
            {
                key:"4",
                title:"牙刷1111",
                note:"爸爸",
                day:"57",
                safe:false,
                normal:true,
                danger:false
            },
            {
                key:"13",
                title:"牙刷11111",
                note:"爸爸",
                day:"57",
                safe:false,
                normal:true,
                danger:false
            },
            {
                key:"14",
                title:"牙刷111111",
                note:"爸爸",
                day:"57",
                safe:false,
                normal:true,
                danger:false
            }
        ]
    },
    {
        id:2,
        genre:"廚房",
        pic:"https://github.com/s110719005/app_final_pic/blob/master/pic_kitchen.png?raw=true",
        todos:[
            {
                key:"5",
                title:"牙刷2",
                note:"爸爸",
                day:"57",
                safe:false,
                normal:true,
                danger:false
            },
            {
                key:"6",
                title:"牙刷22",
                note:"爸爸",
                day:"57",
                safe:true,
                normal:false,
                danger:true
            }
        ]
    },
    {
        id:3,
        genre:"起居",
        pic:"https://github.com/s110719005/app_final_pic/blob/master/pic_bedroom.png?raw=true",
        todos:[
            {
                key:"7",
                title:"牙刷3",
                note:"爸爸",
                day:"57",
                state:1
            },
            {
                key:"8",
                title:"牙刷33",
                note:"爸爸",
                day:"57",
                state:3
            }
        ]
    },
    {
        id:4,
        genre:"其他",
        pic:"https://github.com/s110719005/app_final_pic/blob/master/pic_household.png?raw=true",
        todos:[
            {
                key:"9",
                title:"牙刷4",
                note:"爸爸",
                day:"57",
                state:1
            },
            {
                key:"10",
                title:"牙刷44",
                note:"爸爸",
                day:"57",
                state:3
            }
        ]
    }


];